Плисковский Лавр, ФТ204
kozlov-ma/changemedaddy pull request #3
Opened 2024-03-28 18:37 UTC by L0veR1ck

2024-03-28 18:50 UTC, kozlov-ma requested changes
жутко страшно

2024-03-28 18:50 UTC, kozlov-ma commented on api/api.go
> +func (api API) RunServer() {
Run

2024-03-28 18:50 UTC, kozlov-ma commented on api/idea.go
> +		fmt.Fprintln(w, "bad id")
render

2024-03-28 18:50 UTC, kozlov-ma commented on api/idea.go
> +		w.WriteHeader(404)
render

2024-03-28 18:50 UTC, kozlov-ma commented on api/idea.go
> +	fmt.Fprintf(w, "done with id %v", id)
render...

2024-03-28 18:50 UTC, kozlov-ma commented on api/api.go
> +	PositionProvider
жуткие имена, тем более не надо экспортировать
+ для таких случаев можно сделать один интерфейс Storage например, в который все эти включены

Или интерфейс Storage сразу с этими методами

2024-03-28 18:50 UTC, kozlov-ma commented on api/position.go
> +	if errors.Is(err, db.PositionDoesNotExistError) {
Тут могут быть и другие ошибки

2024-03-28 18:50 UTC, kozlov-ma commented on api/position.go
> +	_ = render.Decode(r, ch)
Ошибка игнорируется

2024-03-28 18:50 UTC, kozlov-ma commented on api/position.go
> +	pos, _ := api.PositionProvider.GetPosition(id, idx)
ошибка игнорируется

2024-03-28 18:50 UTC, kozlov-ma commented on api/position.go
> +	pos = ch.Apply(pos)
изменение применяется без валидации

2024-03-28 18:50 UTC, kozlov-ma commented on api/position.go
> +	if errors.Is(err, db.PositionDoesNotExistError) {
не все ошибки предусмотрены

2024-03-28 18:52 UTC, L0veR1ck commented
ладно()

2024-04-02 17:51 UTC, kozlov-ma requested changes

2024-04-02 17:51 UTC, kozlov-ma commented on api/api.go
>  	r.Use(render.SetContentType(render.ContentTypeJSON))
Content Type JSON а апи возвращает непонятно что

2024-04-02 17:51 UTC, kozlov-ma commented on api/api.go
> +func (api API) Router(r chi.Router) {
зачем экспортировать?

2024-04-02 17:51 UTC, kozlov-ma commented on api/changes.go
> +		_ = api.validate.Struct(ch)
...
Данные валидируются, но результат игнорируется

2024-04-02 17:51 UTC, kozlov-ma commented on api/changes.go
> +		_ = render.DecodeJSON(r.Body, &ch)
Ошибка игнорируется

2024-04-02 17:51 UTC, kozlov-ma commented on api/changes.go
> +		pos, _ := api.db.GetPosition(id)
ошибка игнорируется

2024-04-02 17:51 UTC, kozlov-ma commented on api/changes.go
> +		if errors.Is(err, db.PositionDoesNotExistError) {
не все возможные ошибки учитываются

2024-04-02 17:51 UTC, kozlov-ma commented on api/changes.go
> +		if errors.Is(err, db.PositionDoesNotExistError) {
кстати здесь этой 404 вообще произойти не должно, она должна происходить раньше, но игнорируется

2024-04-02 17:51 UTC, kozlov-ma commented on api/position.go
> +	if err != nil || len(pos.Log) != 0 {
здесь до len(pos.log) != 0 выполнение не дойдет, он не десериализуется

2024-04-02 17:51 UTC, kozlov-ma commented on api/position.go
> +	fmt.Fprintf(w, "done with id %v", id)
content type json

2024-04-05 08:31 UTC, closed without merging